### ISSUE TITLE
Copy-Paste @property

### ISSUE THREAD

**Issue by dev4dev** [RobertGummesson/IntelliPaste-for-XCode#12]
I think it would be great to have ability to copy properties declarations and past them as getters or setters.
Maybe something like this:
* CMD+SHIFT+V -> getters
* CMD+CTRL+SHIFT+V -> setters

**Comment by RobertGummesson** [comment]
That's a good idea. I'll keep that in mind.

**Comment by RobertGummesson** [comment]
Will be closing this one down as a 'won't fix'. I am more or less only developing in Swift these days so the motivation is missing to implement this one.

If anyone is up for it, fork it, implement it and make a pull request. Just reassure it's unit tested first.

**Comment by dev4dev** [comment]
Sadly, but agree :+1:
