### ISSUE TITLE
Xcode 7 update

### ISSUE THREAD

**Issue by phynet** [RobertGummesson/IntelliPaste-for-XCode#17]
Hi, I love your plugin,  is there any possibility to update to Xcode 7?

Thanks :+1:

**Comment by najdanovicivan** [comment]
Check this pull request  https://github.com/RobertGummesson/IntelliPaste-for-XCode/pull/18/files you can modify plugin Info.plist file manually to enable plugin in xcode 7

**Comment by RobertGummesson** [comment]
Ah, I didn't see this until now. This was resolved a day after this one was raised.

**Comment by phynet** [comment]
Thank you Robert!

**Comment by najdanovicivan** [comment]
@RobertGummesson you can also close my pull request.

**Comment by RobertGummesson** [comment]
@najdanovicivan Done. I didn't see your pull request before I made mine. Would have used yours if I did.
