### ISSUE TITLE
no menu no effect

### ISSUE THREAD

**Issue by ForrestAlfred** [RobertGummesson/IntelliPaste-for-XCode#20]
I am using Xcode 7 beta and 7， and installed IntelliPaste justNow, but the no related item ob the Edit Menu

**Comment by RobertGummesson** [comment]
Did you restart Xcode afterwards? The menu item is called 'Paste Intelligently'.

**Comment by ForrestAlfred** [comment]
Yes, I did,  I installed many plugins, maybe something does conflict with it

**Comment by RobertGummesson** [comment]
Hmmm... Did you build from the project or install from Alcatraz? It's working fine for me on Xcode 7.0.

**Comment by ForrestAlfred** [comment]
Thanks, I installed IntelliPaste from Alcatraz before.   Today,  the author of MLAutoReplace reminds me that  maybe the bundle is not loaded. So I built the project again and uninstall from Alcatraz, then reinstall from Alcatraz. And when I reload my Xcode, it comes to remind me find the IntelliPaste plugin bundle. So it works !

**Comment by ForrestAlfred** [comment]
Works perfectly !  I like it, especially the color intelli-paste

**Comment by RobertGummesson** [comment]
Great. Then I'll close the ticket.
